version: '3'
services:
  app:
    container_name: code_igniter-exercise
    image: mobingi/ubuntu-apache2-php7:7.0
    volumes:
      - ../:/var/www/
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 10080:80
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
      - db:/var/lib/mysql
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
volumes:
  db:
