version: '3'
services:
  app:
    build: ./apache-php
    container_name: code_igniter-exercise
    volumes:
      - ../:/var/www/html
    ports:
      - 10080:80
    links:
      - mysql
    depends_on:
      - mysql
    working_dir: /var/www/html
  mysql:
    image: mysql
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
      - db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
volumes:
  db:
